apiVersion: v1
kind: Namespace
metadata:
  name: openshift-insights
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
  labels:
    openshift.io/cluster-monitoring: "true"
    name: openshift-insights
    openshift.io/run-level: "1"
