apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: openshift-insights
  name: operator
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: openshift-insights
  name: gather
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
